Repository cerner/terra-toolkit, pull requests merged in 2018-04, with the labels that each got.

#75 Update docker-compose.yml
  src/wdio/docker-compose.yml
Labels: configuration, enhancement, selenium-docker, webdriver.io

#76 Update docker-compose.yml
  CHANGELOG.md
  src/wdio/docker-compose.yml
Labels: Small, tech-only

#74 Migrate i18n aggregation
  .eslintrc
  bin/aggregate-translations.js
  package-lock.json
  package.json
  scripts/aggregate-translations/aggregate-messages.js
  scripts/aggregate-translations/aggregate-translations-cli.js
  scripts/aggregate-translations/aggregate-translations.js
  scripts/aggregate-translations/generate-translation-file.js
  scripts/aggregate-translations/i18nSupportedLocales.js
  scripts/aggregate-translations/write-aggregated-translations.js
  scripts/aggregate-translations/write-i18n-loaders.js
  tests/jest/__snapshots__/generate-translation-file.test.js.snap
  tests/jest/__snapshots__/write-i18n-loaders.test.js.snap
  tests/jest/aggregate-messages.test.js
  tests/jest/aggregate-translations.test.js
  tests/jest/fixtures/ned_modules/fixtures1/translations/en.json
  tests/jest/fixtures/ned_modules/fixtures1/translations/es.json
  tests/jest/fixtures/ned_modules/fixtures1/translations/pt.json
  tests/jest/fixtures/translations/en.json
  tests/jest/fixtures/translations/es.json
  tests/jest/fixtures/translations/pt.json
  tests/jest/generate-translation-file.test.js
  tests/jest/write-aggregated-translations.test.js
  tests/jest/write-i18n-loaders.test.js
Labels: Large

#81 Terra-Toolkit V3
  .gitignore
  .npmignore
  CHANGELOG.md
  bin/serve-static.js
  bin/serve.js
  config/wdio/wdio.conf.js
  config/webpack/webpack.config.js
  dangerfile.js
  docs/ExpressDevServerService.md
  docs/FAQ.md
  docs/ServeStaticService.md
  docs/TerraToolkitUpgradeGuide-v3.0.0.md
  docs/Wdio_Utility.md
  docs/WebpackDevServerService.md
  package-lock.json
  package.json
  scripts/aggregate-translations/aggregate-translations-cli.js
  scripts/aggregate-translations/aggregate-translations.js
  scripts/serve/README.md
  scripts/serve/loadDefaultWebpackConfig.js
  scripts/serve/serve-cli.js
  scripts/serve/serve-static-cli.js
  scripts/serve/serve-static.js
  scripts/serve/serve.js
  src/nightwatch/nightwatch.config.js
  src/wdio/conf.js
  src/wdio/services/ExpressDevServerService.js
  src/wdio/services/SeleniumDockerService.js
  src/wdio/services/ServeStaticService.js
  src/wdio/services/WebpackDevServerService.js
  src/wdio/services/index.js
  tests/fixtures/compare.html
  tests/fixtures/theme.html
  tests/test.config.js
  wdio.conf.js
Labels: Large, Major Version Bump

#88 Whoops. This config should be pushed to dev-site
  CHANGELOG.md
  config/wdio/wdio.conf.js
  dangerfile.js
  package-lock.json
  wdio.conf.js
Labels: bug

#86 Add service default config to quickly view the defaults
  CHANGELOG.md
  config/wdio/services.default-config.js
  src/wdio/services/AxeService.js
  src/wdio/services/SeleniumDockerService.js
  src/wdio/services/ServeStaticService.js
  tests/fixtures/compare.html
  tests/fixtures/inaccessible-contrast.html
  tests/fixtures/inaccessible-text.html
  tests/fixtures/nightwatch.html
  tests/fixtures/theme.html
Labels: Small

#93 Increase the timeout waiting for the selenium docker service to start
  CHANGELOG.md
  config/wdio/services.default-config.js
Labels: Small
