Repository cerner/terra-toolkit, pull requests merged in 2018-06, with the labels that each got.

#111 Add host option to tt:serve and tt:serve-static
  CHANGELOG.md
  scripts/serve/README.md
  scripts/serve/serve-cli.js
  scripts/serve/serve-static-cli.js
  scripts/serve/serve-static.js
  scripts/serve/serve.js
Labels: Small

#87 Remove terra-dev-site babel exception
  CHANGELOG.md
  config/webpack/webpack.config.js
Labels: Small

#116 Updating webpack.config with PostCSS/UglifyJS corrections
  config/webpack/webpack.config.js
Labels: configuration

#125 Update webpack-merge example
  docs/TerraToolkitUpgradeGuide-v3.0.0.md
Labels: docs
