Repository cerner/terra-toolkit, pull requests merged in 2018-08, with the labels that each got.

#146 Webpack Config Enhancements
  CHANGELOG.md
  config/webpack/webpack.config.js
  jestConfig.js
  package-lock.json
  package.json
  tests/jest/webpack.config.test.js
Labels: configuration

#152 Update default publicPath to be Empty String
  config/webpack/webpack.config.js
  tests/jest/webpack.config.test.js
Labels: bug, configuration

#156 Remove the use of posix path from clean-screenshots
  CHANGELOG.md
  scripts/wdio/clean-screenshots.js
Labels: Small, bug, windows

#159 Switch badges to use badgen-service
  README.md
Labels: docs

#158 Unpin axe-core and bump version to use new bug-fix
  CHANGELOG.md
  package-lock.json
  package.json
Labels: accessibility
