Repository cerner/terra-toolkit, pull requests merged in 2019-01, with the labels that each got.

#225 Update dangerfile
  .travis.yml
  dangerfile.js
Labels: build-tools

#232 Add babel-plugin-syntax-dynamic-import to terra-toolkit
  .babelrc
  package-lock.json
  package.json
Labels: tech-only

#239 enabling docker dev env
  Dockerfile
  docker-compose.yml
  package-lock.json
Labels: build-tools

#242 Adding Duplicate Package Checker Plugin
  CHANGELOG.md
  config/webpack/webpack.config.js
  package-lock.json
  package.json
  tests/jest/webpack.config.test.js
Labels: configuration

#240 Clean Up Axe Service Implementation
  CHANGELOG.md
  package-lock.json
  src/wdio/services/AxeService.js
Labels: axe-service, tech-only
