Repository cerner/terra-toolkit, pull requests merged in 2019-07, with the labels that each got.

#308 Replace dangerjs with probot-changelog
  .github/changelog.yml
  .npmignore
  .travis.yml
  dangerfile.js
  package-lock.json
  package.json
Labels: build-tools, dependency-update

#309 Adding after command helper to help keep dev-site code splitting passive.
  CHANGELOG.md
  package-lock.json
  src/wdio/services/TerraService.js
  tests/fixtures/timeout.html
  tests/test.config.func.js
  tests/wdio/__snapshots__/reference/en/chrome_tiny/timeout-spec/timeout[chain].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/timeout-spec/timeout[refresh].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/timeout-spec/timeout[url-no-param].png
  tests/wdio/__snapshots__/reference/en/chrome_tiny/timeout-spec/timeout[url].png
  tests/wdio/timeout-spec.js
  wdio.conf.js
Labels: webdriver.io

#317 Update postcss-custom-properties to latest release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: dependency-update

#312 Add hideInputCaret wdio test helper
  CHANGELOG.md
  CONTRIBUTORS.md
  docs/Wdio_Utility.md
  src/wdio/services/TerraCommands/hide-input-caret.js
  src/wdio/services/TerraService.js
  tests/fixtures/input.html
  tests/test.config.func.js
  tests/wdio/hideInputCaret-spec.js
  wdio.conf.js
Labels: docs, enhancement, terra-service
