Repository cerner/terra-toolkit, pull requests merged in 2019-11, with the labels that each got.

#349 Exit wdio test run if webpack fails to compile
  CHANGELOG.md
  src/wdio/services/ServeStaticService.js
Labels: enhancement

#355 Fix Mismatch Tolerance when 0
  CHANGELOG.md
  src/wdio/services/TerraCommands/determine-test-options.js
  tests/jest/determine-test-options.test.js
Labels: bug-fix

#357 Update Duplicate Checker List
  CHANGELOG.md
  config/webpack/webpack.config.js
Labels: configuration, webpack
